var CONSTANTS = {
        changesSuccess: "Changes Saved Successfully",
        photoDeleted: "Photo Deleted Successfully",
        invalidFile: "Please note only JPEG and PNG images are acceptable",
        maxDamagePhotoLimit: "Maximum damage photos allowed is 15. Please select no more than 15 damage photos",
        maxPhotoUploadSize: "Maximum limit for Photo upload size is 15 MB",
        serverError: "Server Error",
        tryAgain: "Please Try Again...",
        serverErrorTryAgain: "Server Error Please Try Again...",
        maxLenCellphone: "Cell phone number should be 10 digits",
        requiredFields: "Please Enter All Required Fields",
        somethingWentWrong: "Something went wrong, please try again. If issue persists navigate to 'Dashboard" +
                        "', open the inspection from 'Pending Inspections' and continue",
        notApproved: "Not Approved Please Try again...",
        rejected: "Rejected",
        approved: "Approved",
        incorrectCredential: "Username or password is incorrect.",
        copyPasteNotAllowed: "Copy & Paste is not allowed",
        invalidEmailId: "Invalid Email Address",
        inspectionReportSent: "Inspection Report Sent to Registered Email Address Successfully",
        reEnterVIN: "Invalid VIN - Please re-enter VIN",
        inspectorSigNotSaved: "Inspector Signature Not Saved...",
        inspectorSigSaved: "Inspector Signature Saved Successfully",
        inspectorSigRequired: "Please provide the Inspector signature",
        serverErrorDownloadPdf: "Server Error in Download PDF",
        maxWinDamagePhotosLimit: "Maximum Windshield Damage Photos allowed is 6. Kindly delete excess photos from " +
                        "'Selected Photos' tray",
        maxWinFullPhotosLimit: "Maximum Full Windshield Photos allowed is 3. Kindly delete excess photos from 'S" +
                        "elected Photos' tray",
        emailSent: "Mail Sent Successfully, Please Check Your Mail Id",
        fillRequiredField: "Please Enter All Required Fields Of Vehicle Condition Form",
        photoNotSaved: "Photo Not Saved Successfully, Please Try Again...",
        photosUploaded: "Photos Uploaded Successfully",
        insuredSigNotSaved: "Insured Signature Not Saved...",
        insuredSigSaved: "Insured Signature Saved Successfully",
        sigNotSaved: "Signature Not Saved...",
        sigSaved: "Signature Saved Successfully",
        sigRequired: "Please provide the signature",
        maxLimitExceeded: "Maximum Limit Exceeded in Entry Field",
        userNotExist: "User does not exist",
        insuredSigRequired: "Please provide the Insured signature",
        photoSaved: "Photo Saved Successfully",
        maxWinFullPhotosLimitShort: "Maximum limit for Full Windshield Photos is 3",
        maxWinDamagePhotosLimitShort: "Maximum limit for damage photo is 6",
        winInspectionFlorida: 'Windshield Inspection is not eligible for your state. Please contact CARCO help ' +
                        'desk for more information',
        VINRequired: "Please Enter Required Field of Vehicle Identification Number Form",
        reportNumberRequired: "Please Enter Report Number",
        wrongReportNumber: "Wrong Report Number Pattern",
        invalidReportNumber: "Invalid Report Number",
        selectPhotoForQCRetake: "Report Number is valid, Please select photo for QC Re-take",
        qcPhotoUploaded: "QC Re-take has been successfully submitted to CARCO",
        qcEpaStickerNotSaved: "QC EPA Sticker Not Saved Successfully, Please Try Again...",
        qcRearPassengerNotSaved: "QC Rear and Passenger Side Photo Not Saved Successfully, Please Try Again...",
        qcFrontDriverNotSaved: "QC Front and Driver Side Photo Not Saved Successfully, Please Try Again...",
        registrationSuccessful: "Registration is successful. An e-mail with Username and Password has been sent t" +
                        "o registered e-mail ID",
        registrationFailed: "Registration Failed",
        allReadyRegistered: "User is already registered with this email ID",
        damagePhotosNotSaved: "Damage Photo(s) Not Saved Successfully, Please Try Again...",
        frontDriverPhotoNotSaved: "Front and Driver Side Photo Not Saved Successfully, Please Try Again...",
        rearPassengerNotSaved: "Rear and Passenger Side Photo Not Saved Successfully, Please Try Again...",
        epaStickerNotSaved: "EPA Sticker Not Saved Successfully, Please Try Again...",
        passwordChanged: "Password changed successfully",
        winDamageFormRequired: "Please Enter All Required Fields Of Windshield Damage Section Form",
        // winInsuredFormRequired: "Please Enter All Required Fields Of Windshield
        // Insured Info Form",
        maxWinFullPhotos: "Maximum Windshield Full Photos allowed is 3. Please select no more than 3 Windsh" +
                        "ield Full Photos.",
        maxWinDamagePhotos: "Maximum damage photos allowed is 6. Please select no more than 6 damage photos.",
        maxwinDamagePhotoLimit: "Maximum limit for Windshield Damage photos is 6",
        oldPasswordIncorrect: "Old password is incorrect",
        selectOneCheckboxFromAntiTheft: "Please mark at least one checkbox from Anti-Theft Device section",
        vehicleOptionsFormRequired: "Please Enter All Required Fields Of Vehicle Options Form",
        selectOneCheckboxFromPhysicalDamage: "Please mark at least one checkbox from Physical Condition Or Damage section",
        winSelectOneCheckboxFromPhysicalCondition: "Please mark at least one checkbox from Physical Condition Of Windshield section",
        checkAntiTheft: "Please Check Anti-Theft Device section",
        vehicleOptionFormRequired: "Please Enter All Required Fields Of Vehicle Option Form",
        photoAutoApproved: '30-Second Timer got Over, the Photo has been Auto-Approved.',
        sessionExpired: 'Your session has timed out. Please log in again',
        accessDenied: 'Access denied for this report.',
        qcPhotoNotSaved: "QC Re-take has not been successfully submitted to CARCO, Please Try Again...",
        AIFaliure: 'Could not connect to server...',
        HEPhotoPicked: 'This photo has been picked by another human expert, please pick next avaliable p' +
                        'hoto'
};